- name: Install ufw
  apt:
    name: ufw

- name: Enable ufw
  ufw:
    state: enabled    

- name: Deny incoming
  ufw:
    direction: incoming
    policy: deny

- name: Allow outgoing
  ufw:
    direction: outgoing
    policy: allow

- name: Allow ssh
  ufw:
    rule: limit
    port: ssh
    proto: tcp