- name: Install ufw
  ansible.builtin.apt:
    name: ufw

- name: Enable ufw
  ansible.builtin.ufw:
    state: enabled

- name: Deny incoming
  ansible.builtin.ufw:
    direction: incoming
    policy: deny
  notify: Reload ufw

- name: Allow outgoing
  ansible.builtin.ufw:
    direction: outgoing
    policy: allow
  notify: Reload ufw

- name: Allow ssh
  ansible.builtin.ufw:
    rule: limit
    port: ssh
    proto: tcp
  notify: Reload ufw

- name: Flush handlers
  ansible.builtin.meta: flush_handlers