---
- name: Update packages
  ansible.builtin.apt:
    cache_valid_time: 86400
    update_cache: yes
- name: Import locales tasks
  ansible.builtin.import_tasks: locales.yml
  tags: locales
- name: Import firewall tasks
  ansible.builtin.import_tasks: firewall.yml
  tags: firewall
- name: Import ntp tasks
  ansible.builtin.import_tasks: ntp.yml
  tags: ntp
- name: Import ssh tasks
  ansible.builtin.import_tasks: sshd.yml
  tags: sshd
- name: Import 2fa tasks
  ansible.builtin.import_tasks: 2fa.yml
  tags: 2fa
- name: Import update tasks
  ansible.builtin.import_tasks: updates.yml
  tags: updates
- name: Import user tasks
  ansible.builtin.import_tasks: users.yml
  tags: users
