- name: Install ntp
  apt:
    name: ntp

- name: Enable ntp
  service:
    name: ntp
    enabled: true
    state: started

- name: Allow 123/tcp
  ufw:
    rule: allow
    port: ntp
    direction: out
  notify: Reload ufw