- name: Install ntp
  ansible.builtin.apt:
    name: ntp

- name: Enable ntp
  ansible.builtin.service:
    name: ntp
    enabled: true
    state: started

- name: Allow 123/tcp
  community.general.ufw:
    rule: allow
    port: ntp
    direction: out
  notify: Reload ufw