- name: Install sshd
  apt:
    name: openssh-server

- name: Enable sshd
  service:
    name: ssh
    enabled: true
    state: started

- name: Harden sshd
  lineinfile:
    path: "/etc/ssh/sshd_config"
    regex: "^(#)?{{ item.key }}"
    line: "{{ item.key }} {{ item.value }}"
    state: present
  loop:
    - { key: "AllowUsers", value: "{{ users | map(attribute='name')| join(' ') }}" }
    - { key: "ClientAliveInterval", value: "300" }
    - { key: "MaxAuthTries", value: "3" }
    - { key: "PasswordAuthentication", value: "no" }
    - { key: "PermitEmptyPasswords", value: "no" }
    - { key: "PermitRootLogin", value: "no" }
    - { key: "Protocol", value: "2" }
  notify:
    - Restart sshd