- name: Install unattended-upgrades
  apt:
    name: unattended-upgrades

- name: Configure unattended-upgrades
  copy:
    src: "50unattended-upgrades"
    dest: "/etc/apt/apt.conf.d/50unattended-upgrades"
    mode: 0644

- name: Configure update frequency
  lineinfile:
    path: "/etc/apt/apt.conf.d/20auto-upgrades"
    regex: '{{ item.key }}'
    line: '{{ item.key }} "{{ item.value }}";'
    state: present
  loop:
    - { key: "APT::Periodic::Update-Package-Lists", value: "1" }
    - { key: "APT::Periodic::Unattended-Upgrade", value: "1" }
    - { key: "APT::Periodic::Download-Upgradeable-Packages", value: "1" }
    - { key: "APT::Periodic::AutocleanInterval", value: "7" }
