---

- name: Configure each user
  become: yes
  become_user: "{{ user.name }}"
  block:
    - name: Create $HOME/.ansible/tmp directory
      ansible.builtin.file:
        path: "$HOME/.ansible/tmp"
        state: directory
        mode: 0700

    - name: Check if ohmyzsh directory exists
      ansible.builtin.stat:
        path: "$HOME/.oh-my-zsh"
      register: ohmyzsh_dir

    - name: Install ohmyzsh
      ansible.builtin.git:
        repo: "https://github.com/robbyrussell/oh-my-zsh.git"
        dest: "$HOME/.oh-my-zsh"
        depth: 1
        version: master
      when: user.shell == '/bin/zsh' and not ohmyzsh_dir.stat.exists

    - name: Install homeshick
      ansible.builtin.git:
        repo: "https://github.com/andsens/homeshick.git"
        dest: "$HOME/.homesick/repos/homeshick"
        version: master
      when: user.dotfiles is defined and user.dotfiles

    - name: Check if dotfiles directory exists
      ansible.builtin.stat:
        path: "$HOME/.homesick/repos/dotfiles"
      register: dotfiles_dir

    - name: Install dotfiles
      ansible.builtin.shell: |
        set -euo pipefail
        echo "y y" | $HOME/.homesick/repos/homeshick/bin/homeshick clone {{ item.dotfiles }}
      args:
        executable: /bin/bash
      when: item.dotfiles is defined and user.dotfiles and not dotfiles_dir.stat.exists

    - name: Set authorized keys
      ansible.posix.authorized_key:
        user: "{{ user.name }}"
        state: present
        key: "{{ user.key_url }}"
      when: user.key_url is defined
