- name: Install dependencies
  apt:
    name:
      - zsh
      - git

- name: Create users
  user:
    name: "{{ item.name }}"
    password: "{{ item.password }}"
    shell: "{{ item.shell }}"
  loop: "{{ users }}"
  when: users is defined

- name: Add to sudoers
  user:
    name: "{{ item.name }}"
    group: "sudo"
    append: yes
  loop: "{{ users }}"
  when: users is defined and item.sudo is defined and item.sudo

- name: Setup users
  include_tasks: user.yml
  vars:
    user: "{{ item }}"
  loop: "{{ users }}"
  when: users is defined