- name: Install dependencies
  ansible.builtin.apt:
    name:
      - zsh
      - git

- name: Create users
  ansible.builtin.user:
    name: "{{ item.name }}"
    password: "{{ item.password }}"
    shell: "{{ item.shell }}"
  loop: "{{ users }}"
  when: users is defined
  no_log: True

- name: Add to sudoers
  ansible.builtin.user:
    name: "{{ item.name }}"
    groups: "sudo"
    append: yes
  loop: "{{ users }}"
  when:
    - users is defined
    - item.sudo is defined
    - item.sudo

- name: Setup users
  include_tasks: user.yml
  vars:
    user: "{{ item }}"
  loop: "{{ users }}"
  when: users is defined