- name: Install dependencies
  apt:
    name:
      - zsh
      - git

- name: Create users
  user:
    name: "{{ item.name }}"
    password: "{{ item.password }}"
    shell: "{{ item.shell }}"
  loop: "{{ users }}"

- name: Download ohmyzsh
  get_url:
    url: https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh
    dest: /tmp/ohmyzsh.sh
    mode: o+rwx

- name: Setup users
  include_tasks: user.yml
  vars:
    user: "{{ item }}"
  loop: "{{ users }}"